### ISSUE TITLE
block form: image popover menu lost (ccm-popover-menu-container)

### ISSUE THREAD

**Issue by headland** [ExchangeCore/Concrete5-CKEditor#50] opened 2016-05-31 16:42 UTC
Hallo,

first, we are very happy that you create this solution! Since this year we are building pages with 5.7 for our customers. Unfortunately we have many problems with redactor in block forms: in Safari or Chrome we cannot paste some text to the cursor position of an existing text ... it always appears on first position ... and in Firefox or IE the pull-down menus (format for example) are flickering when the base page is not in scroll position top = 0.

Now we are using this CKEditor package (in forms of custom blocks) ... and everything works fine except this little problem: If you are using the image selector in the same form you can add an image, but after that you don't get the popover menu to change or clear this image.
In the source code the div id=ccm-popover-menu-container is empty now and no error or warning in the console of the browser.
I would appreciate any ideas ... so that we can create a workaround.

thanks, Toni from headland

**Comment by joe-meyer** [comment] 2016-05-31 22:19
@headland would it be possible for you to point us at the code for your custom block you created so we could witness the issue? CKEditor is going to be the new editor as of concrete5 version 8, so we'd like to iron out any bugs we can, but being able to easily replicate it will help us greatly.

**Comment by headland** [comment] 2016-06-01 12:51
Sure. The block is attached ...
[artikel_std.zip](https://github.com/ExchangeCore/Concrete5-CKEditor/files/293406/artikel_std.zip)

**Comment by headland** [comment] 2016-06-03 11:19
For interested developers: As a quick workaround to work with, uninstall the package and init the editor manually. Include the js `<script src="/packages/community_ckeditor/vendor/ckeditor/ckeditor.js"></script>`... create a textarea ... and make the editor work with `<script>CKEDITOR.replace( 'textarea_id' );</script>`. (Also in this case changing the config.js will have no effect.) // Toni

**Comment by joe-meyer** [comment] 2016-06-04 22:45
This is definitely a confirmed issue. So far what I've been able to identify is that it has to do with the CSS override we put in place in /assets/concrete5filemanager/styles.css.

The reason this is there is because without it, when you open up the file manager from the ckeditor file manager, the file manager ends up behind the ckeditor dialog. We need to find a better way to scope on that dialog specifically so that we aren't causing these sorts of issues elsewhere.

**Comment by joe-meyer** [comment] 2016-06-04 23:09
This should be fixed by 98de980bf9000a791b33d2cbc58e8ef690da2cd0

Thanks for reporting!

**Closed as completed by joe-meyer** 2016-06-04 23:09 UTC
Labels: type-bug, priority-medium

**Comment by headland** [comment] 2016-06-06 09:49
Good work!
